// Generated by rstantools.  Do not edit by hand.

/*
    sampinfo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    sampinfo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with sampinfo.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_mm10d01_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_mm10d01");
    reader.add_event(92, 90, "end", "model_mm10d01");
    return reader;
}
#include <stan_meta_header.hpp>
class model_mm10d01 : public prob_grad {
private:
        int deltaM_value;
        int C;
        int K;
        int N;
        int S;
        int Q;
        std::vector<int> sID;
        std::vector<int> qID;
        std::vector<matrix_d> X;
        std::vector<int> cID;
public:
    model_mm10d01(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_mm10d01(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_mm10d01_namespace::model_mm10d01";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "deltaM_value", "int", context__.to_vec());
            deltaM_value = int(0);
            vals_i__ = context__.vals_i("deltaM_value");
            pos__ = 0;
            deltaM_value = vals_i__[pos__++];
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "C", "int", context__.to_vec());
            C = int(0);
            vals_i__ = context__.vals_i("C");
            pos__ = 0;
            C = vals_i__[pos__++];
            check_greater_or_equal(function__, "C", C, 2);
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 0);
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "S", "int", context__.to_vec());
            S = int(0);
            vals_i__ = context__.vals_i("S");
            pos__ = 0;
            S = vals_i__[pos__++];
            check_greater_or_equal(function__, "S", S, 1);
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "Q", "int", context__.to_vec());
            Q = int(0);
            vals_i__ = context__.vals_i("Q");
            pos__ = 0;
            Q = vals_i__[pos__++];
            check_greater_or_equal(function__, "Q", Q, 1);
            current_statement_begin__ = 10;
            validate_non_negative_index("sID", "N", N);
            context__.validate_dims("data initialization", "sID", "int", context__.to_vec(N));
            sID = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("sID");
            pos__ = 0;
            size_t sID_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < sID_k_0_max__; ++k_0__) {
                sID[k_0__] = vals_i__[pos__++];
            }
            size_t sID_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < sID_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "sID[i_0__]", sID[i_0__], 0);
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("qID", "N", N);
            context__.validate_dims("data initialization", "qID", "int", context__.to_vec(N));
            qID = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("qID");
            pos__ = 0;
            size_t qID_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < qID_k_0_max__; ++k_0__) {
                qID[k_0__] = vals_i__[pos__++];
            }
            size_t qID_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < qID_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "qID[i_0__]", qID[i_0__], 0);
            }
            current_statement_begin__ = 12;
            validate_non_negative_index("X", "C", C);
            validate_non_negative_index("X", "K", K);
            validate_non_negative_index("X", "N", N);
            context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(N,C,K));
            X = std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(N, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(C, K));
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_j_2_max__ = K;
            size_t X_j_1_max__ = C;
            size_t X_k_0_max__ = N;
            for (size_t j_2__ = 0; j_2__ < X_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < X_k_0_max__; ++k_0__) {
                        X[k_0__](j_1__, j_2__) = vals_r__[pos__++];
                    }
                }
            }
            current_statement_begin__ = 13;
            validate_non_negative_index("cID", "N", N);
            context__.validate_dims("data initialization", "cID", "int", context__.to_vec(N));
            cID = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("cID");
            pos__ = 0;
            size_t cID_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < cID_k_0_max__; ++k_0__) {
                cID[k_0__] = vals_i__[pos__++];
            }
            size_t cID_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < cID_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "cID[i_0__]", cID[i_0__], 1);
                check_less_or_equal(function__, "cID[i_0__]", cID[i_0__], C);
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 17;
            validate_non_negative_index("alpha_raw", "(C - 1)", (C - 1));
            validate_non_negative_index("alpha_raw", "Q", Q);
            num_params_r__ += ((C - 1) * Q);
            current_statement_begin__ = 18;
            validate_non_negative_index("beta_mu", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 19;
            validate_non_negative_index("beta_s_sd", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 20;
            validate_non_negative_index("beta_q_sd", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 21;
            validate_non_negative_index("beta_q_raw", "K", K);
            validate_non_negative_index("beta_q_raw", "Q", Q);
            num_params_r__ += (K * Q);
            current_statement_begin__ = 22;
            validate_non_negative_index("beta_s_raw", "K", K);
            validate_non_negative_index("beta_s_raw", "S", S);
            num_params_r__ += (K * S);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_mm10d01() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 17;
        if (!(context__.contains_r("alpha_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha_raw");
        pos__ = 0U;
        validate_non_negative_index("alpha_raw", "(C - 1)", (C - 1));
        validate_non_negative_index("alpha_raw", "Q", Q);
        context__.validate_dims("parameter initialization", "alpha_raw", "matrix_d", context__.to_vec((C - 1),Q));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> alpha_raw((C - 1), Q);
        size_t alpha_raw_j_2_max__ = Q;
        size_t alpha_raw_j_1_max__ = (C - 1);
        for (size_t j_2__ = 0; j_2__ < alpha_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_raw_j_1_max__; ++j_1__) {
                alpha_raw(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(alpha_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 18;
        if (!(context__.contains_r("beta_mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_mu");
        pos__ = 0U;
        validate_non_negative_index("beta_mu", "K", K);
        context__.validate_dims("parameter initialization", "beta_mu", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_mu(K);
        size_t beta_mu_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_mu_j_1_max__; ++j_1__) {
            beta_mu(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta_mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 19;
        if (!(context__.contains_r("beta_s_sd")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_s_sd missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_s_sd");
        pos__ = 0U;
        validate_non_negative_index("beta_s_sd", "K", K);
        context__.validate_dims("parameter initialization", "beta_s_sd", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_s_sd(K);
        size_t beta_s_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_s_sd_j_1_max__; ++j_1__) {
            beta_s_sd(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, beta_s_sd);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_s_sd: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 20;
        if (!(context__.contains_r("beta_q_sd")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_q_sd missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_q_sd");
        pos__ = 0U;
        validate_non_negative_index("beta_q_sd", "K", K);
        context__.validate_dims("parameter initialization", "beta_q_sd", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_q_sd(K);
        size_t beta_q_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_q_sd_j_1_max__; ++j_1__) {
            beta_q_sd(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, beta_q_sd);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_q_sd: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 21;
        if (!(context__.contains_r("beta_q_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_q_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_q_raw");
        pos__ = 0U;
        validate_non_negative_index("beta_q_raw", "K", K);
        validate_non_negative_index("beta_q_raw", "Q", Q);
        context__.validate_dims("parameter initialization", "beta_q_raw", "matrix_d", context__.to_vec(K,Q));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_q_raw(K, Q);
        size_t beta_q_raw_j_2_max__ = Q;
        size_t beta_q_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_q_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_q_raw_j_1_max__; ++j_1__) {
                beta_q_raw(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(beta_q_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_q_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 22;
        if (!(context__.contains_r("beta_s_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_s_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_s_raw");
        pos__ = 0U;
        validate_non_negative_index("beta_s_raw", "K", K);
        validate_non_negative_index("beta_s_raw", "S", S);
        context__.validate_dims("parameter initialization", "beta_s_raw", "matrix_d", context__.to_vec(K,S));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_s_raw(K, S);
        size_t beta_s_raw_j_2_max__ = S;
        size_t beta_s_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_s_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_s_raw_j_1_max__; ++j_1__) {
                beta_s_raw(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.matrix_unconstrain(beta_s_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_s_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 17;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> alpha_raw;
            (void) alpha_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha_raw = in__.matrix_constrain((C - 1), Q, lp__);
            else
                alpha_raw = in__.matrix_constrain((C - 1), Q);
            current_statement_begin__ = 18;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_mu;
            (void) beta_mu;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_mu = in__.vector_constrain(K, lp__);
            else
                beta_mu = in__.vector_constrain(K);
            current_statement_begin__ = 19;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_s_sd;
            (void) beta_s_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_s_sd = in__.vector_lb_constrain(0, K, lp__);
            else
                beta_s_sd = in__.vector_lb_constrain(0, K);
            current_statement_begin__ = 20;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_q_sd;
            (void) beta_q_sd;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_q_sd = in__.vector_lb_constrain(0, K, lp__);
            else
                beta_q_sd = in__.vector_lb_constrain(0, K);
            current_statement_begin__ = 21;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> beta_q_raw;
            (void) beta_q_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_q_raw = in__.matrix_constrain(K, Q, lp__);
            else
                beta_q_raw = in__.matrix_constrain(K, Q);
            current_statement_begin__ = 22;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> beta_s_raw;
            (void) beta_s_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_s_raw = in__.matrix_constrain(K, S, lp__);
            else
                beta_s_raw = in__.matrix_constrain(K, S);
            // transformed parameters
            current_statement_begin__ = 26;
            validate_non_negative_index("alpha", "C", C);
            validate_non_negative_index("alpha", "Q", Q);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> alpha(C, Q);
            stan::math::initialize(alpha, DUMMY_VAR__);
            stan::math::fill(alpha, DUMMY_VAR__);
            current_statement_begin__ = 27;
            validate_non_negative_index("theta", "C", C);
            validate_non_negative_index("theta", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> theta(C, N);
            stan::math::initialize(theta, DUMMY_VAR__);
            stan::math::fill(theta, DUMMY_VAR__);
            current_statement_begin__ = 28;
            validate_non_negative_index("beta", "K", K);
            validate_non_negative_index("beta", "S", S);
            validate_non_negative_index("beta", "Q", Q);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > beta(Q, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>(K, S));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 29;
            if (as_bool(logical_gt(K, 0))) {
                current_statement_begin__ = 30;
                for (int q = 1; q <= Q; ++q) {
                    current_statement_begin__ = 31;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(q), stan::model::nil_index_list()), 
                                add(add(rep_matrix(beta_mu, S), diag_pre_multiply(beta_s_sd, beta_s_raw)), rep_matrix(elt_multiply(beta_q_sd, stan::model::rvalue(beta_q_raw, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(q), stan::model::nil_index_list())), "beta_q_raw")), S)), 
                                "assigning variable beta");
                }
            }
            current_statement_begin__ = 37;
            stan::model::assign(alpha, 
                        stan::model::cons_list(stan::model::index_min_max(1, (C - 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), 
                        divide(alpha_raw, 2), 
                        "assigning variable alpha");
            current_statement_begin__ = 38;
            stan::model::assign(alpha, 
                        stan::model::cons_list(stan::model::index_uni(C), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), 
                        to_row_vector(rep_array(0, Q)), 
                        "assigning variable alpha");
            current_statement_begin__ = 41;
            if (as_bool(logical_gt(K, 0))) {
                current_statement_begin__ = 42;
                for (int n = 1; n <= N; ++n) {
                    current_statement_begin__ = 43;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                multiply(get_base1(X, n, "X", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_uni(get_base1(qID, n, "qID", 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(get_base1(sID, n, "sID", 1)), stan::model::nil_index_list()))), "beta")), 
                                "assigning variable theta");
                }
                current_statement_begin__ = 45;
                stan::math::assign(theta, add(theta, stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_multi(qID), stan::model::nil_index_list())), "alpha")));
            } else {
                current_statement_begin__ = 47;
                stan::math::assign(theta, stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_multi(qID), stan::model::nil_index_list())), "alpha"));
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 26;
            size_t alpha_j_1_max__ = C;
            size_t alpha_j_2_max__ = Q;
            for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(alpha(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: alpha" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable alpha: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 27;
            size_t theta_j_1_max__ = C;
            size_t theta_j_2_max__ = N;
            for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(theta(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: theta" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable theta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 28;
            size_t beta_k_0_max__ = Q;
            size_t beta_j_1_max__ = K;
            size_t beta_j_2_max__ = S;
            for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                        if (stan::math::is_uninitialized(beta[k_0__](j_1__, j_2__))) {
                            std::stringstream msg__;
                            msg__ << "Undefined transformed parameter: beta" << "[" << k_0__ << "]" << "(" << j_1__ << ", " << j_2__ << ")";
                            stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                        }
                    }
                }
            }
            // model body
            current_statement_begin__ = 53;
            lp_accum__.add(std_normal_log<propto__>(beta_mu));
            current_statement_begin__ = 54;
            lp_accum__.add(std_normal_log<propto__>(beta_q_sd));
            current_statement_begin__ = 55;
            lp_accum__.add(std_normal_log<propto__>(beta_s_sd));
            current_statement_begin__ = 56;
            lp_accum__.add(std_normal_log<propto__>(to_vector(beta_q_raw)));
            current_statement_begin__ = 57;
            lp_accum__.add(std_normal_log<propto__>(to_vector(beta_s_raw)));
            current_statement_begin__ = 58;
            lp_accum__.add(std_normal_log<propto__>(to_vector(alpha_raw)));
            current_statement_begin__ = 60;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 61;
                lp_accum__.add(categorical_logit_log<propto__>(get_base1(cID, n, "cID", 1), stan::model::rvalue(theta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), "theta")));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("alpha_raw");
        names__.push_back("beta_mu");
        names__.push_back("beta_s_sd");
        names__.push_back("beta_q_sd");
        names__.push_back("beta_q_raw");
        names__.push_back("beta_s_raw");
        names__.push_back("alpha");
        names__.push_back("theta");
        names__.push_back("beta");
        names__.push_back("log_lik");
        names__.push_back("dev_m");
        names__.push_back("beta_qdev");
        names__.push_back("beta_sdev");
        names__.push_back("beta_q_temp");
        names__.push_back("beta_s_temp");
        names__.push_back("beta_qmean");
        names__.push_back("beta_smean");
        names__.push_back("deltaM");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back((C - 1));
        dims__.push_back(Q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(Q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(S);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(C);
        dims__.push_back(Q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(C);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Q);
        dims__.push_back(K);
        dims__.push_back(S);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(Q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(S);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(Q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(S);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_mm10d01_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> alpha_raw = in__.matrix_constrain((C - 1), Q);
        size_t alpha_raw_j_2_max__ = Q;
        size_t alpha_raw_j_1_max__ = (C - 1);
        for (size_t j_2__ = 0; j_2__ < alpha_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_raw_j_1_max__; ++j_1__) {
                vars__.push_back(alpha_raw(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_mu = in__.vector_constrain(K);
        size_t beta_mu_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_mu_j_1_max__; ++j_1__) {
            vars__.push_back(beta_mu(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_s_sd = in__.vector_lb_constrain(0, K);
        size_t beta_s_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_s_sd_j_1_max__; ++j_1__) {
            vars__.push_back(beta_s_sd(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_q_sd = in__.vector_lb_constrain(0, K);
        size_t beta_q_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_q_sd_j_1_max__; ++j_1__) {
            vars__.push_back(beta_q_sd(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_q_raw = in__.matrix_constrain(K, Q);
        size_t beta_q_raw_j_2_max__ = Q;
        size_t beta_q_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_q_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_q_raw_j_1_max__; ++j_1__) {
                vars__.push_back(beta_q_raw(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_s_raw = in__.matrix_constrain(K, S);
        size_t beta_s_raw_j_2_max__ = S;
        size_t beta_s_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_s_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_s_raw_j_1_max__; ++j_1__) {
                vars__.push_back(beta_s_raw(j_1__, j_2__));
            }
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 26;
            validate_non_negative_index("alpha", "C", C);
            validate_non_negative_index("alpha", "Q", Q);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> alpha(C, Q);
            stan::math::initialize(alpha, DUMMY_VAR__);
            stan::math::fill(alpha, DUMMY_VAR__);
            current_statement_begin__ = 27;
            validate_non_negative_index("theta", "C", C);
            validate_non_negative_index("theta", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> theta(C, N);
            stan::math::initialize(theta, DUMMY_VAR__);
            stan::math::fill(theta, DUMMY_VAR__);
            current_statement_begin__ = 28;
            validate_non_negative_index("beta", "K", K);
            validate_non_negative_index("beta", "S", S);
            validate_non_negative_index("beta", "Q", Q);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > beta(Q, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, S));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 29;
            if (as_bool(logical_gt(K, 0))) {
                current_statement_begin__ = 30;
                for (int q = 1; q <= Q; ++q) {
                    current_statement_begin__ = 31;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(q), stan::model::nil_index_list()), 
                                add(add(rep_matrix(beta_mu, S), diag_pre_multiply(beta_s_sd, beta_s_raw)), rep_matrix(elt_multiply(beta_q_sd, stan::model::rvalue(beta_q_raw, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(q), stan::model::nil_index_list())), "beta_q_raw")), S)), 
                                "assigning variable beta");
                }
            }
            current_statement_begin__ = 37;
            stan::model::assign(alpha, 
                        stan::model::cons_list(stan::model::index_min_max(1, (C - 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), 
                        divide(alpha_raw, 2), 
                        "assigning variable alpha");
            current_statement_begin__ = 38;
            stan::model::assign(alpha, 
                        stan::model::cons_list(stan::model::index_uni(C), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), 
                        to_row_vector(rep_array(0, Q)), 
                        "assigning variable alpha");
            current_statement_begin__ = 41;
            if (as_bool(logical_gt(K, 0))) {
                current_statement_begin__ = 42;
                for (int n = 1; n <= N; ++n) {
                    current_statement_begin__ = 43;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                multiply(get_base1(X, n, "X", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_uni(get_base1(qID, n, "qID", 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(get_base1(sID, n, "sID", 1)), stan::model::nil_index_list()))), "beta")), 
                                "assigning variable theta");
                }
                current_statement_begin__ = 45;
                stan::math::assign(theta, add(theta, stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_multi(qID), stan::model::nil_index_list())), "alpha")));
            } else {
                current_statement_begin__ = 47;
                stan::math::assign(theta, stan::model::rvalue(alpha, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_multi(qID), stan::model::nil_index_list())), "alpha"));
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t alpha_j_2_max__ = Q;
                size_t alpha_j_1_max__ = C;
                for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                        vars__.push_back(alpha(j_1__, j_2__));
                    }
                }
                size_t theta_j_2_max__ = N;
                size_t theta_j_1_max__ = C;
                for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                        vars__.push_back(theta(j_1__, j_2__));
                    }
                }
                size_t beta_j_2_max__ = S;
                size_t beta_j_1_max__ = K;
                size_t beta_k_0_max__ = Q;
                for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                        for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                            vars__.push_back(beta[k_0__](j_1__, j_2__));
                        }
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 66;
            validate_non_negative_index("log_lik", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(N);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 67;
            double dev_m;
            (void) dev_m;  // dummy to suppress unused var warning
            stan::math::initialize(dev_m, DUMMY_VAR__);
            stan::math::fill(dev_m, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("beta_qdev", "K", K);
            validate_non_negative_index("beta_qdev", "Q", Q);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_qdev(K, Q);
            stan::math::initialize(beta_qdev, DUMMY_VAR__);
            stan::math::fill(beta_qdev, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("beta_sdev", "K", K);
            validate_non_negative_index("beta_sdev", "S", S);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_sdev(K, S);
            stan::math::initialize(beta_sdev, DUMMY_VAR__);
            stan::math::fill(beta_sdev, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("beta_q_temp", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta_q_temp(K);
            stan::math::initialize(beta_q_temp, DUMMY_VAR__);
            stan::math::fill(beta_q_temp, DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("beta_s_temp", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta_s_temp(K);
            stan::math::initialize(beta_s_temp, DUMMY_VAR__);
            stan::math::fill(beta_s_temp, DUMMY_VAR__);
            current_statement_begin__ = 72;
            validate_non_negative_index("beta_qmean", "K", K);
            validate_non_negative_index("beta_qmean", "Q", Q);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_qmean(K, Q);
            stan::math::initialize(beta_qmean, DUMMY_VAR__);
            stan::math::fill(beta_qmean, DUMMY_VAR__);
            current_statement_begin__ = 73;
            validate_non_negative_index("beta_smean", "K", K);
            validate_non_negative_index("beta_smean", "S", S);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta_smean(K, S);
            stan::math::initialize(beta_smean, DUMMY_VAR__);
            stan::math::fill(beta_smean, DUMMY_VAR__);
            current_statement_begin__ = 74;
            int deltaM;
            (void) deltaM;  // dummy to suppress unused var warning
            stan::math::fill(deltaM, std::numeric_limits<int>::min());
            stan::math::assign(deltaM,deltaM_value);
            // generated quantities statements
            current_statement_begin__ = 75;
            stan::math::assign(dev_m, 0);
            current_statement_begin__ = 76;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 77;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            categorical_logit_log(get_base1(cID, n, "cID", 1), stan::model::rvalue(theta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), "theta")), 
                            "assigning variable log_lik");
                current_statement_begin__ = 78;
                stan::math::assign(dev_m, (dev_m + (-(2) * get_base1(log_lik, n, "log_lik", 1))));
            }
            current_statement_begin__ = 80;
            stan::math::assign(beta_qdev, diag_pre_multiply(beta_q_sd, beta_q_raw));
            current_statement_begin__ = 81;
            stan::math::assign(beta_sdev, diag_pre_multiply(beta_s_sd, beta_s_raw));
            current_statement_begin__ = 82;
            if (as_bool(logical_gt(K, 0))) {
                current_statement_begin__ = 83;
                for (int k = 1; k <= K; ++k) {
                    current_statement_begin__ = 84;
                    stan::model::assign(beta_q_temp, 
                                stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                                mean(to_array_1d(stan::model::rvalue(beta_qdev, stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "beta_qdev"))), 
                                "assigning variable beta_q_temp");
                    current_statement_begin__ = 85;
                    stan::model::assign(beta_s_temp, 
                                stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                                mean(to_array_1d(stan::model::rvalue(beta_sdev, stan::model::cons_list(stan::model::index_uni(k), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "beta_sdev"))), 
                                "assigning variable beta_s_temp");
                }
                current_statement_begin__ = 87;
                stan::math::assign(beta_qmean, add(rep_matrix(add(beta_mu, beta_s_temp), Q), beta_qdev));
                current_statement_begin__ = 88;
                stan::math::assign(beta_smean, add(rep_matrix(add(beta_mu, beta_q_temp), S), beta_sdev));
            }
            // validate, write generated quantities
            current_statement_begin__ = 66;
            size_t log_lik_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
            current_statement_begin__ = 67;
            vars__.push_back(dev_m);
            current_statement_begin__ = 68;
            size_t beta_qdev_j_2_max__ = Q;
            size_t beta_qdev_j_1_max__ = K;
            for (size_t j_2__ = 0; j_2__ < beta_qdev_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_qdev_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_qdev(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 69;
            size_t beta_sdev_j_2_max__ = S;
            size_t beta_sdev_j_1_max__ = K;
            for (size_t j_2__ = 0; j_2__ < beta_sdev_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_sdev_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_sdev(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 70;
            size_t beta_q_temp_j_1_max__ = K;
            for (size_t j_1__ = 0; j_1__ < beta_q_temp_j_1_max__; ++j_1__) {
                vars__.push_back(beta_q_temp(j_1__));
            }
            current_statement_begin__ = 71;
            size_t beta_s_temp_j_1_max__ = K;
            for (size_t j_1__ = 0; j_1__ < beta_s_temp_j_1_max__; ++j_1__) {
                vars__.push_back(beta_s_temp(j_1__));
            }
            current_statement_begin__ = 72;
            size_t beta_qmean_j_2_max__ = Q;
            size_t beta_qmean_j_1_max__ = K;
            for (size_t j_2__ = 0; j_2__ < beta_qmean_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_qmean_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_qmean(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 73;
            size_t beta_smean_j_2_max__ = S;
            size_t beta_smean_j_1_max__ = K;
            for (size_t j_2__ = 0; j_2__ < beta_smean_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_smean_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_smean(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 74;
            vars__.push_back(deltaM);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_mm10d01";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t alpha_raw_j_2_max__ = Q;
        size_t alpha_raw_j_1_max__ = (C - 1);
        for (size_t j_2__ = 0; j_2__ < alpha_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_raw_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha_raw" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_mu_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_mu_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_mu" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_s_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_s_sd_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_s_sd" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_q_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_q_sd_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_q_sd" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_q_raw_j_2_max__ = Q;
        size_t beta_q_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_q_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_q_raw_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_q_raw" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_s_raw_j_2_max__ = S;
        size_t beta_s_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_s_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_s_raw_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_s_raw" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t alpha_j_2_max__ = Q;
            size_t alpha_j_1_max__ = C;
            for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "alpha" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t theta_j_2_max__ = N;
            size_t theta_j_1_max__ = C;
            for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t beta_j_2_max__ = S;
            size_t beta_j_1_max__ = K;
            size_t beta_k_0_max__ = Q;
            for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "beta" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "dev_m";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_qdev_j_2_max__ = Q;
        size_t beta_qdev_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_qdev_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_qdev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_qdev" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_sdev_j_2_max__ = S;
        size_t beta_sdev_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_sdev_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_sdev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_sdev" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_q_temp_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_q_temp_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_q_temp" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_s_temp_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_s_temp_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_s_temp" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_qmean_j_2_max__ = Q;
        size_t beta_qmean_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_qmean_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_qmean_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_qmean" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_smean_j_2_max__ = S;
        size_t beta_smean_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_smean_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_smean_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_smean" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "deltaM";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t alpha_raw_j_2_max__ = Q;
        size_t alpha_raw_j_1_max__ = (C - 1);
        for (size_t j_2__ = 0; j_2__ < alpha_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < alpha_raw_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha_raw" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_mu_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_mu_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_mu" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_s_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_s_sd_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_s_sd" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_q_sd_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_q_sd_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_q_sd" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_q_raw_j_2_max__ = Q;
        size_t beta_q_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_q_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_q_raw_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_q_raw" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_s_raw_j_2_max__ = S;
        size_t beta_s_raw_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_s_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_s_raw_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_s_raw" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t alpha_j_2_max__ = Q;
            size_t alpha_j_1_max__ = C;
            for (size_t j_2__ = 0; j_2__ < alpha_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "alpha" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t theta_j_2_max__ = N;
            size_t theta_j_1_max__ = C;
            for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t beta_j_2_max__ = S;
            size_t beta_j_1_max__ = K;
            size_t beta_k_0_max__ = Q;
            for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "beta" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "dev_m";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_qdev_j_2_max__ = Q;
        size_t beta_qdev_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_qdev_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_qdev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_qdev" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_sdev_j_2_max__ = S;
        size_t beta_sdev_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_sdev_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_sdev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_sdev" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_q_temp_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_q_temp_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_q_temp" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_s_temp_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_s_temp_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_s_temp" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_qmean_j_2_max__ = Q;
        size_t beta_qmean_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_qmean_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_qmean_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_qmean" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_smean_j_2_max__ = S;
        size_t beta_smean_j_1_max__ = K;
        for (size_t j_2__ = 0; j_2__ < beta_smean_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_smean_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_smean" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "deltaM";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_mm10d01_namespace::model_mm10d01 stan_model;
#endif
